# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DMSScrollViewStudy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DMSScrollViewStudy

  target 'DMSScrollViewStudyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'SnapKit'
  pod 'Then'
  target 'DMSScrollViewStudyUITests' do
    # Pods for testing
  end
end
